### ISSUE TITLE
Handle AutoConnect being on by default in tinc1.1 pre17

### ISSUE THREAD

**Issue by Teteros** [ThePredatorBG/contra-launcher#12]
AutoConnect is on by default as of https://github.com/gsliepen/tinc/commit/01cb1961eac33de9e9d9cecd0910850a2cb549c3 (tinc 1.1 pre17)

We can just explicitly add `AutoConnect = yes` instead of no in https://github.com/ThePredatorBG/contra-launcher/blob/master/VPNForm.cs#L110 to turn it on for us by default as well.

**Comment by ThePredatorBG** [comment]
Thanks, done.
