### ISSUE TITLE
Enable tap interface before trying to start tinc

### ISSUE THREAD

**Issue by Teteros** [ThePredatorBG/contra-launcher#13]
Users can have the ContraVPN network interface disabled which causes the VPN to fail to start:

Before starting tinc, we can check if the interface is disabled by running netsh:
`netsh interface show interface ContraVPN`

Outputs:
```
ContraVPN
   Type:                 Dedicated
   Administrative state: Disabled
   Connect state:        Disconnected
```
If disabled, we can enable it with:
`netsh interface set interface ContraVPN enable`

**Comment by ThePredatorBG** [comment]
Done.
