### ISSUE TITLE
Print output of tinc join (in case it fails)

### ISSUE THREAD

**Issue by Teteros** [ThePredatorBG/contra-launcher#14]
A user tried to `join` on an invite through launcher and it crashed ![crash](https://cdn.discordapp.com/attachments/208259866870022145/522107825917263921/unknown.png)]

The cause was most likely their firewall as manual `join` via the tinc console times out ![timeout](https://cdn.discordapp.com/attachments/208259866870022145/522110444316655627/unknown.png)

Printing at least the last line of `tinc join` would be a good idea for debugging purposes (or if `not succesful`) The crash here on invite confirm might have to do with it or is unrelated.

**Comment by ThePredatorBG** [comment]
I put a try-catch block and displayed a message on fail.
