### ISSUE TITLE
Add checks for necessary host file

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#17]
![img](https://cdn.discordapp.com/attachments/194127262793203712/525336477794566144/unknown.png)
VPN will not start if `contravpn` host file is missing for some reason, maybe the user deleted it on accident.

We can just check for that file before running vpn to make launcher more robust.
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
Bonus points if we could download the current host file form a gist or similar.

**Comment by ThePredatorBG** [comment]
Just check and display a message if missing?

**Comment by Teteros** [comment]
> Just check and display a message if missing?

Yeah that will do for time being, other stuff is extra.

**Comment by ThePredatorBG** [comment]
Done.
