### ISSUE TITLE
Integrate ContraVPN into Launcher

### ISSUE THREAD

**Issue by Teteros** [ThePredatorBG/contra-launcher#2]
# Front end to the Tinc command-line.

Commands used by tinc to join the `contravpn` network are 
- `join` for accepting tinc pre-release invites
- `start` to start the VPN
Button to open tinc console by starting `tinc.exe` directly would also be handy.

`TAP-WINDOWS` adapter install may or may not be done through the launcher, up for discussion.

ContraVPN docs:
https://gist.github.com/Teteros/1d4feaa2c0e1c04697c6f68a4a39d4cc

**Comment by Teteros** [comment]
@ThePredatorBG If you implented most of this already you can upload it to the repo and add a comment
`Closes #2` to close this issue automatically.

**Comment by ThePredatorBG** [comment]
@Teteros Command-line parameters implemented as three buttons on the top left. Button graphics are placeholders until we decide the integration is complete (it's the last step). I suggest we add a new small button which will lead to instructions and explanation on how to set ContraVPN up. It could be a new gist. We need to decide how we are going to handle adapter installation and invites.

**Comment by Teteros** [comment]
f892c1271d1e66ae245a5c8aa78b9ec82ae11a9f and ealier commits, integrate a good portion of the functionality now.
