### ISSUE TITLE
Options.ini location is not detected properly

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#21]
On some machines path for Options.ini seems to be resolved to just Documents folder rather than `Command and Conquer Generals Zero Hour Data`

Tweaking LeafPath does not change this, might be environment variable used being different on some systems.
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by ThePredatorBG** [comment]
I would need someone with this problem to show me his ZH registry.

**Comment by Teteros** [comment]
Change

`SOFTWARE\Wow6432Node\Electronic Arts\EA Games\Command and Conquer Generals Zero Hour`

to

`SOFTWARE\Electronic Arts\EA Games\Command and Conquer Generals Zero Hour`

when 32 bit OS is detected :smile:
