### ISSUE TITLE
Tinc does not start if folder path contains unicode characters

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#27]
![img](https://cdn.discordapp.com/attachments/208259866870022145/532721884777938944/unknown.png)

![img2](https://cdn.discordapp.com/attachments/208259866870022145/532720316531867659/unknown.png)

Simple workaround is to just move `tinc.pid` and `tinc.log` files to `vpnconfig\contravpn` location as well, those should be english (ascii).
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by ThePredatorBG** [comment]
What about all the users who already have **tinc.pid** and **tinc.log** in contra\vpn?

**Comment by Teteros** [comment]
Those files are generated at runtime by tinc so no need to do anything.

**Comment by ThePredatorBG** [comment]
What was that defaulting to: _--pidfile=tinc.pid_?
Can I replace:
_--pidfile=\"" + Environment.CurrentDirectory + "\\contra\\vpn\\tinc.pid\"_
with
_--pidfile=tinc.pid_?
In the OpenConsole method we use _tinc.StartInfo.Arguments = "--config=\"" + Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\Contra\\vpnconfig\\contravpn\" **--pidfile=tinc.pid**";_

**Comment by Teteros** [comment]
[vpnconfig](https://github.com/ThePredatorBG/contra-launcher/blob/master/Form1.cs#L264) path is used for tinc.log and tinc.pid in 76e5419. So this can be closed.
