### ISSUE TITLE
Change version lookup source.

### ISSUE THREAD

**Issue by ThePredatorBG** [ThePredatorBG/contra-launcher#28]
Reminder to change version lookup source in later versions (currently using URL to gist), so that 1.0.0.0 does not attempt to download newer versions (as it cannot and bugs out). Thus, 1.0.0.0 users will always stay on 1.0.0.0.

**Comment by Teteros** [comment]
Might be a good time to ditch the gist link entirely and move the version/MOTD file to repo itself, used on newer launchers.
