### ISSUE TITLE
Handle missing .url files

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#29]
![img](https://cdn.discordapp.com/attachments/194127262793203712/534419605813198885/unknown.png)

Warn user the .url file wasn't extracted
Maybe fallback to hardcoded link instead.
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
No need to handle .url's if they don't exist :smile: (as of 76e5419ca5ab00f615829cccd3b51dfe6e9e9fc6)
