### ISSUE TITLE
"Application not found" in links

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#34]
![img](https://cdn.discordapp.com/attachments/194127262793203712/542820346688962560/unknown.png)

Seems try/catch for explorer.exe calls doesn't work as intended.
Checking for ExitCode instead was confimed to be working, e.g:
```cs
Process url = new Process();
url.StartInfo.FileName = "explorer.exe";
url.StartInfo.Arguments = "https://contra.cncguild.net";
url.Start();
if (url.ExitCode != 0) MessageBox.Show("Browser didn't start", "Error");
```
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
The above error message still appears, then the custom MessageBox though.
