### ISSUE TITLE
Add camera height tweak to launcher

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#43]
Too many people asking for it:
- doing it incorrectly
- using old versions of tweak
- using ZH camtweak

it would be easier for us to just expose this in launcher and receive less mismatch complaints.

Can use sane values (e.g slider from default to about 2x normal) in more options menu.
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by ThePredatorBG** [comment]
Will close it when Patch 2 releases. Some final touches need to be done before the release.

**Comment by Teteros** [comment]
Done
