### ISSUE TITLE
Investigate INIZH.big

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#51]
That file comes with retail version of Zero Hour, we're not doing anything about it but a user reported it caused issues with their came starting up.

Maybe it would be a good to install patch 1 to a clean ZH install to investigate.
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
>with their game*

Discord Ref: https://discordapp.com/channels/194120076054495232/194128451848896514/551190600804991026
