### ISSUE TITLE
"Remove redundant subnet restrictions"

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#62]
Upon initial testing it looks like hosts which have not obtained a DHCP IP address (10.10.10.0/24 range), and instead are using the self-assigned link-local address (169.254.0.0/16) can connect fine both ways.
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by Teteros** [comment]
At least on the new server, might need more testing with users behind NAT.

If all is fine we can toss the "unknown" or "Not compatible" labels when launcher checks for IP and just use the 10.10.10.X or 169.254.X.X IP the tap adapter gives us saved directly to Options.ini

**Comment by Teteros** [comment]
It was confirmed that adding an appropriate route (e.g `route ADD 10.10.10.0 MASK 255.255.255.0 0.0.0.0`) helps making self-addressed adapters connect with DHCP acquired ones.
Discord ref: https://discordapp.com/channels/194120076054495232/194128451848896514/565603690434527245

Implementing the route if contacting DHCP server failed is a possibility but that's for another issue.

**Comment by Teteros** [comment]
No longer relevant with ZeroTier as new VPN.
