### ISSUE TITLE
Error - "Cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by ContraTeam** [ThePredatorBG/contra-launcher#65]
When we're doing `File.Move()` in a bunch of places it's possible to get that error.

Likely when renaming Install_Final.bmp files and so on, needs more checks?
---
*Beep, boop, this issue was created by: Teteros.*

**Comment by ThePredatorBG** [comment]
How to reproduce? Is there such issue with Patch 1 launcher?

**Comment by Teteros** [comment]
Whenever the user manually installed the files before running launcher.
**AND** the .ctr files from the archive are already present so the rename fails
![image](https://user-images.githubusercontent.com/5067989/56852278-10e03380-6911-11e9-8be5-9f86a75c4fc6.png)

Perhaps we could run `File.Delete()` before trying to rename if the file already exists.
