### ISSUE TITLE
Move tincvpn key storage outside game dir

### ISSUE THREAD

**Issue by Teteros** [ThePredatorBG/contra-launcher#9]
It's common for users to reinstall their game or unknowingly duplicate their private/public keypair when copying their game files around.

The former requires users to be reinvited again and the latter can cause collisions when multiple tinc daemons are open simultanously, because of same identity being used.

We can tell tinc to use the (machine-specific) properties folder that the launcher already uses in
e.g: `%LOCALAPPDATA%\Contra`
which is less prone to change.

For this we only really need to tweak the `--config` parameter. Tinc binaries/logfile/pidfile and devcon/tap drivers can stay in game dir.

`--config` is where tinc looks for keys/`hosts` and tinc.conf so this is ideal.

We can still use gamedir tinc config as a fallback if appdata configuration is missing of course, then users who already have tinc set up need no manual changes.

**Comment by ThePredatorBG** [comment]
Done.
